"""Canonical grammar particles and reviewed English mapping tables."""


def load_grammar_state(self) -> None:
    """Attach immutable grammar configuration to a Xenari facade."""
    # Particles from spec §2.3
    self.p = {
        "subj": "ka", "obj": "ra", "verb": "ta", "loc": "na", "goal": "fa",
        "inst": "mo", "anim": "vi", "inan": "nu",
        "past": "lo", "fut": "ve", "pres": "sa", "hab": "du", "pot": "pe", "imp": "ko",
        "wit": "xa", "infr": "xe", "rep": "xi", "assum": "xo", "mir": "zu",
        "neg": "ngu", "foc": "pli", "conc": "truq", "q": "va",
        "sub": "su", "endsub": "ti", "pl": "ha", "poss": "po",
        "and": "xen", "or": "noq", "but": "kex",
    }

    # Ordinal pronouns (spec §2.4). The numeric keys match the canon
    # ordinal labels so English mappings cannot silently swap readings.
    self.pronouns = {
        "1": "neq",   # I/me
        "2": "mex",   # you
        "3": "leq",   # present other
        "4": "req",   # absent known other
        "5": "seq",   # unknown/foreign other
        "6": "zeq",   # indefinite/abstract other
    }

    # English does not encode Xenari ordinal context. Bare they/them/their
    # default to plural known others (req ha), never inferred zeq.
    self.en_pronouns = {
        "i": ("1", False), "me": ("1", False), "my": ("1", True), "mine": ("1", True),
        "we": ("1", False, True), "us": ("1", False, True), "our": ("1", True, True),
        "you": ("2", False), "your": ("2", True), "yours": ("2", True),
        "he": ("3", False), "him": ("3", False), "his": ("3", True),
        "she": ("3", False), "her": ("3", False), "hers": ("3", True),
        "it": ("3", False), "its": ("3", True),
        "they": ("4", False, True), "them": ("4", False, True),
        "their": ("4", True, True), "theirs": ("4", True, True),
    }

    self.tense_map = {
        "pres": "sa", "present": "sa",
        "past": "lo", "ed": "lo", "was": "lo", "were": "lo", "had": "lo", "did": "lo",
        "future": "ve", "will": "ve", "shall": "ve", "would": "ve",
        "habitual": "du", "usually": "du", "often": "du", "always": "du",
        "potential": "pe", "could": "pe", "might": "pe", "may": "pe",
        "imperative": "ko",
    }

    self.evidential_map = {
        "witnessed": "xa", "saw": "xa",
        "inferred": "xe",
        "reported": "xi", "heard": "xi",
        "assumed": "xo",
        "mirative": "zu", "surprise": "zu",
    }

    # Common English verbs that exist in the lexicon
    # We check these against the lexicon at runtime
    # English -> Xenari verb roots (from actual lexicon)
    self.verb_map = {
        "want": "glemp", "desire": "glemp",
        "wants": "glemp", "wanted": "glemp",
        "love": "zrent", "loved": "zrent",
        "loves": "zrent",
        "fuck": "qroz",
        "fucks": "qroz",
        "fucking": "qroz",
        "need": "qemp",
        "needs": "qemp",
        "needed": "qemp",
        "have": "xrong",
        "has": "xrong",
        "had": "xrong",
        "eat": "xlof",
        "eats": "xlof",
        "ate": "xlof",
        "go": "qeng",
        "goes": "qeng",
        "going": "qeng",
        "went": "qeng",
        "approach": "frig",
        "approaches": "frig",
        "approached": "frig",
        "blow": "qruq",
        "blows": "qruq",
        "blew": "qruq",
        "blown": "qruq",
        "come": "di",
        "comes": "di",
        "came": "di",
        "run": "zaqa",
        "runs": "zaqa",
        "ran": "zaqa",
        "walk": "kroc",
        "walks": "kroc",
        "walked": "kroc",
        "fall": "hup",
        "falls": "hup",
        "fell": "hup",
        "stop": "semax",
        "stops": "semax",
        "stopped": "semax",
        "start": "qe",
        "starts": "qe",
        "started": "qe",
        "bite": "qruq'",
        "bites": "qruq'",
        "bit": "qruq'",
        "say": "krimp",
        "says": "krimp",
        "said": "krimp",
        "tell": "slimp",
        "tells": "slimp",
        "told": "slimp",
        "cook": "krol",
        "fix": "mlun",
        "build": "mrob",
        "built": "mrob",
        "teach": "nyec",
        "learn": "qlef",
        "drink": "qlup",
        "know": "quh",
        "find": "trek",
        "finds": "trek",
        "found": "trek",
        "destroy": "sri",
        "lose": "tric",
        "pull": "xram",
        "push": "hrag",
        "hide": "co",
        "open": "xleq",
        "opens": "xleq",
        "opened": "xleq",
        "close": "qrak",
        "make": "qlemp",
        "shape": "qlemp",
        "grow": "qlax",
        "break": "zont",
        "broke": "zont",
        "broken": "zont",
        "dream": "qax",
        "think": "bre",
        "change": "xreq",
        "ask": "prant",
        "write": "vlex",
        "inscribe": "vlex",
        "roleplay": "frez",
        "pretend": "frez",
        "submit": "prad",
        "yield": "prad",
        "kiss": "nquxe",
        "kisses": "nquxe",
        "kissed": "nquxe",
        "need": "qemp",
        "see": "toq",
        "sees": "toq",
        "seeing": "toq",
        "saw": "toq",
        "seen": "toq",
        "look": "toq",
        "looks": "toq",
        "looked": "toq",
        "watch": "toq",
        "watches": "toq",
        "watched": "toq",
        "hear": "cromq",
        "hears": "cromq",
        "heard": "cromq",
        "listen": "grip",
        "listens": "grip",
        "whisper": "tyequga",
        "whispers": "tyequga",
        "whispered": "tyequga",
        "speak": "zuqra",
        "speaks": "zuqra",
        "spoke": "zuqra",
        "talk": "zuqra",
        "talks": "zuqra",
        "sleep": "pramx",
        "sleeps": "pramx",
        "slept": "pramx",
        "rest": "ezlolax",
        "rests": "ezlolax",
        "rested": "ezlolax",
        "kill": "sri",
        "send": "bern",
        "sends": "bern",
        "sent": "bern",
        "give": "flux",
        "gives": "flux",
        "gave": "flux",
        "given": "flux",
        "take": "treq",
        "takes": "treq",
        "took": "treq",
        "taken": "treq",
        "put": "xlom",
        "sit": "bezli",
        "sits": "bezli",
        "sat": "bezli",
        "stand": "cirku",
        "stands": "cirku",
        "stood": "cirku",
        "touch": "qabrerd",
        "touched": "qabrerd",
        "slam": "tulo",
        "slammed": "tulo",
        "wait": "trekq",
        "help": "pegzos",
        "helps": "pegzos",
        "helped": "pegzos",
        "hurt": "zont",
        "burn": "xraq",
        "work": "qxundraz",
        "works": "qxundraz",
        "worked": "qxundraz",
        "working": "qxundraz",
        "operate": "qxundraz",
        "operates": "qxundraz",
        "operated": "qxundraz",
        "operating": "qxundraz",
        "throw": "qranx",
        "throws": "qranx",
        "throwing": "qranx",
        "threw": "qranx",
        "thrown": "qranx",
        "decode": "nimixu",
        "decodes": "nimixu",
        "decoded": "nimixu",
        "decoding": "nimixu",
        "decipher": "nimixu",
        "deciphers": "nimixu",
        "deciphered": "nimixu",
        "deciphering": "nimixu",
        "translate": "nrotm",
        "translates": "nrotm",
        "translated": "nrotm",
        "translating": "nrotm",
        "enter": "logi",
        "enters": "logi",
        "entered": "logi",
        "belong": "mifzxuri",
        "belongs": "mifzxuri",
        "belonged": "mifzxuri",
        "get": "smite",
        "gets": "smite",
        "got": "smite",
        "gotten": "smite",
        "getting": "smite",
    }

    self.copula_words = {"is", "are", "am", "be", "was", "were", "being", "feel"}

    # English function words to skip (not nouns, not verbs)
    self.skip_words = {"the", "a", "an", "to", "of", "in", "on", "at", "by", "for",
                       "with", "from", "as", "that", "this", "these", "those",
                       "it", "its", "so", "very", "just", "really", "also",
                       "about", "into", "through", "during", "before", "after",
                       "above", "below", "up", "down", "out", "over", "under",
                       "again", "further", "then", "once", "here", "there",
                       "all", "any", "both", "each", "few", "more", "most",
                       "other", "some", "such", "only", "own", "same", "than",
                       "too", "s", "t", "can", "should", "now", "today",
                       "yesterday", "tomorrow", "tonight"}
